Repository ErrorCode-510/PandaOffice_front, pull requests merged in 2024-07, with the labels that each got.

#37 Feature/30 e approval document view
  panda-office/src/components/e_approval/DocumentTable.js
  panda-office/src/components/e_approval/E_Approval.css
  panda-office/src/pages/e_approval/E_Approval.css
  panda-office/src/pages/e_approval/E_ApprovalLayout.js
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/E_ApprovalSidebar.js
Labels: 기능구현잇슈, 편승준

#39 [기능구현] 면접자 목록 조회 구
  panda-office/src/App.js
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/modules/index.js
  panda-office/src/pages/recruitment/PagingBar.js
  panda-office/src/pages/recruitment/RecruitmentLayout.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/recruitment/RecruitmentSidebar.js
  panda-office/src/pages/recruitment/applicant/Applicant.js
  panda-office/src/pages/recruitment/applicant/ApplicantInfoTitle.js
  panda-office/src/pages/recruitment/applicant/ApplicantList.js
  panda-office/src/pages/recruitment/applicant/ApplicantListItem.js
  panda-office/src/pages/recruitment/applicant/ApplicantSearch.js
  panda-office/src/pages/recruitment/recruitment.css
Labels: 기능구현잇슈, 성우현

#42 [기능구현] 면접자 목록 조회 구현 수정
  panda-office/src/components/common/Footer.js
  panda-office/src/pages/recruitment/applicant/Applicant.js
  panda-office/src/pages/recruitment/recruitment.css
Labels: 꾸며봣슈, 성우현

#44 [기능구현]인사부서 급여자료입력 페이지 구현
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/pages/Employee/Payroll/EmplPayroll.css
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
  panda-office/src/pages/Employee/Payroll/MyPay.css
  panda-office/src/pages/Employee/Payroll/MyPay.js
Labels: 꾸며봣슈, 이유란

#45 [기능구현] 폴더 crud, 결재 양식 상태 업데이트
  panda-office/src/apis/E_ApprovalAPICalls.js
  panda-office/src/apis/e_approval/ApprovalDocumentFolderAPICalls.js
  panda-office/src/components/e_approval/DocumentTable.js
  panda-office/src/components/e_approval/E_Approval.css
  panda-office/src/components/e_approval/template/FolderManager.js
  panda-office/src/components/e_approval/template/TemplateFolder.js
  panda-office/src/components/e_approval/template/TemplateManager.js
  panda-office/src/components/e_approval/template/TemplateTable.js
  panda-office/src/modules/E_ApprovalModules.js
  panda-office/src/pages/e_approval/E_Approval.css
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/E_ApprovalSidebar.js
  panda-office/src/pages/e_approval/documentTemplate/E_ApprovalTemplateFolder.js
Labels: 기능구현잇슈, 편승준

#48 [기능 설계] 면접자 정보 수정 구현
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/recruitment/applicant/Applicant.js
  panda-office/src/pages/recruitment/applicant/ApplicantList.js
  panda-office/src/pages/recruitment/applicant/ApplicantListItem.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantSearch.js
  panda-office/src/pages/recruitment/recruitment.css
Labels: 기능구현잇슈, 성우현

#53 [기능 설계 면접자 정보 삭제 구현
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/pages/recruitment/RecruitmentSidebar.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
Labels: 기능구현잇슈, 성우현

#49 [기능구현] 공지사항 전체공지 목록페이지 구현
  .idea/dataSources.xml
  package-lock.json
  panda-office/src/App.js
  panda-office/src/components/common/Navbar.js
  panda-office/src/modules/index.js
  panda-office/src/pages/Employee/EmployeeLayout.js
  panda-office/src/pages/Employee/Payroll/MyPay.css
  panda-office/src/pages/notice/NoticeDetail.js
  panda-office/src/pages/notice/NoticeLayout.js
  panda-office/src/pages/notice/NoticeList.js
  panda-office/src/pages/notice/NoticeListItem.js
  panda-office/src/pages/notice/NoticePagingBar.js
  panda-office/src/pages/notice/NoticeRoutes.js
  panda-office/src/pages/notice/NoticeSidebar.js
  panda-office/src/pages/notice/notice.css
Labels: 기능구현잇슈, 김민준

#54 Feature/52 post applicant
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/pages/recruitment/ConfirmationModal.js
  panda-office/src/pages/recruitment/RecruitmentSidebar.js
  panda-office/src/pages/recruitment/applicant/Applicant.js
  panda-office/src/pages/recruitment/applicant/ApplicantCreateModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/recruitment.css
Labels: 기능구현잇슈, 성우현

#57 [기능구현] 공지사항 전체공지 목록페이지 구현(수정)
  panda-office/src/apis/NoticeAPICalls.js
  panda-office/src/modules/NoticeModules.js
  panda-office/src/pages/notice/Notice.js
Labels: 기능구현잇슈, 김민준

#59 [기타수정] MyPay.css 재업로드
  panda-office/src/pages/Employee/Payroll/MyPay.js
Labels: 기타사항잇슈, 이유란

#61 [기능 설게] 면접일정 등록 폼 스타일 구현
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/components/common/Navbar.js
  panda-office/src/pages/recruitment/ConfirmationModal.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/recruitment/RecruitmentSidebar.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/recruitment.css
  panda-office/src/pages/recruitment/schedule/Schedule.js
  panda-office/src/pages/recruitment/schedule/ScheduleCreate.js
  panda-office/src/utils/CalendarApi.js
Labels: 성우현, 기능설계

#69 [기능구현] 결재 양식 등록 기본적인 기능 구현
  panda-office/src/apis/e_approval/ApprovalDocumentTemplateAPICalls.js
  panda-office/src/components/e_approval/template/TemplateEditor.js
  panda-office/src/components/e_approval/template/components/AddNewLine.js
  panda-office/src/components/e_approval/template/components/AddNewLinePreview.js
  panda-office/src/components/e_approval/template/components/ApprovalBox.js
  panda-office/src/components/e_approval/template/components/ApprovalDocumentSetting.js
  panda-office/src/components/e_approval/template/components/DraftBox.js
  panda-office/src/components/e_approval/template/components/DraftInfo.js
  panda-office/src/components/e_approval/template/components/WebEditor.js
  panda-office/src/components/e_approval/templateFolder/FolderManager.js
  panda-office/src/components/e_approval/templateFolder/TemplateFolder.js
  panda-office/src/components/e_approval/templateFolder/TemplateManager.js
  panda-office/src/components/e_approval/templateFolder/TemplateTable.js
  panda-office/src/modules/E_ApprovalModules.js
  panda-office/src/pages/e_approval/E_Approval.css
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/documentTemplate/E_ApprovalTemplateFolder.js
  panda-office/src/pages/e_approval/documentTemplate/E_ApprovalTemplateRegist.js
Labels: 기능구현잇슈, 편승준

#63 [기능구현]근태 관리 페이지 틀 제작
  panda-office/src/pages/attendance/AttendanceLayout.js
  panda-office/src/pages/attendance/AttendanceRoutes.js
  panda-office/src/pages/attendance/AttendanceSidebar.js
  panda-office/src/pages/attendance/annualLeaveCalendar/AnnualLeaveCalendar.js
  panda-office/src/pages/attendance/annualleaveadjustment/AnnualLeaveAdjustment.js
  panda-office/src/pages/attendance/annualleaverecord/AnnualLeaveRecord.js
  panda-office/src/pages/attendance/attendancerequeststatus/AttendanceRequestStatus.js
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.css
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.js
Labels: 기능구현잇슈, 손석현

#62 [기능 설계] 입력 폼 스타일, 컴포넌트 분리 사용
  panda-office/src/pages/recruitment/schedule/ScheduleCreate.js
  panda-office/src/pages/recruitment/schedule/ScheduleForm.js
Labels: 꾸며봣슈, 성우현

#70 [기능구현] 사원 정보 수정 기능 구현
  panda-office/public/index.html
  panda-office/src/pages/Employee/AddNewEmployee.js
  panda-office/src/pages/Employee/EditEmployee.js
  panda-office/src/pages/Employee/Employee.css
  panda-office/src/pages/Employee/EmployeeList.js
Labels: 기능구현잇슈, 김아연

#65 [중간점검] 프로젝트 병합준비
  panda-office/src/apis/PayrollAPICalls.js
  panda-office/src/modules/PayrollModules.js
  panda-office/src/modules/index.js
  panda-office/src/pages/Employee/EmployeeRoutes.js
  panda-office/src/pages/Employee/EmployeeSidebar.js
  panda-office/src/pages/Employee/Payroll/EmplPayroll.css
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
  panda-office/src/pages/Employee/Payroll/MyPay.css
  panda-office/src/pages/Employee/Payroll/MyPay.js
Labels: 테스트잇슈, 이유란

#71 [기능구현] 근태 상태 현황 틀 짜기
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.css
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.js
Labels: 기능구현잇슈, 손석현

#73 [기능구현] 급여 자료 입력 데이터 삽입
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
Labels: 기능구현잇슈, 이유란

#74 [기능구현] 공지사항 데이터 상세페이지 전송 구현
  panda-office/src/apis/NoticeAPICalls.js
  panda-office/src/modules/NoticeModules.js
  panda-office/src/pages/notice/Notice.js
  panda-office/src/pages/notice/NoticeDetail.js
  panda-office/src/pages/notice/NoticeLayout.js
  panda-office/src/pages/notice/NoticeList.js
  panda-office/src/pages/notice/NoticeListItem.js
  panda-office/src/pages/notice/NoticeRoutes.js
  panda-office/src/pages/notice/detailNotice/NoticeDetail.js
  panda-office/src/pages/notice/notice.css
Labels: 기능구현잇슈, 김민준

#78 [오류수정] 급여, 공지사항 임포트 관련 오류 해결
  panda-office/src/modules/PayrollModules.js
  panda-office/src/pages/notice/NoticeRoutes.js
Labels: 버그해결햇슈, 편승준

#80 [ 기능구현] 내 연차 내역 페이지 틀 제작
  panda-office/src/pages/attendance/annualleaverecord/AnnualLeaveRecord.css
  panda-office/src/pages/attendance/annualleaverecord/AnnualLeaveRecord.js
  panda-office/src/pages/attendance/annualleaverecord/Current.js
  panda-office/src/pages/attendance/annualleaverecord/Search.js
Labels: 기능구현잇슈, 손석현

#86 [기능설계] 면접일정 캘린더 한글화 및 '일' 제거 캘린더 db 연동 조회 구현
  panda-office/src/apis/InterviewScheduleAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/modules/InterviewScheduleModules.js
  panda-office/src/modules/index.js
  panda-office/src/pages/Employee/Payroll/MyPay.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/recruitment/RecruitmentSidebar.js
  panda-office/src/pages/recruitment/applicant/Applicant.js
  panda-office/src/pages/recruitment/applicant/ApplicantCreateModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/recruitment.css
  panda-office/src/pages/recruitment/schedule/Intertviewer.js
  panda-office/src/pages/recruitment/schedule/InterviewerAddList.js
  panda-office/src/pages/recruitment/schedule/Schedule.js
  panda-office/src/pages/recruitment/schedule/ScheduleModal.js
  panda-office/src/utils/CalendarApi.js
Labels: 기능구현잇슈, 성우현

#89 [기능구현] 전체 사원 급여조회 데이터 등록
  package-lock.json
  panda-office/src/apis/PayrollAPICalls.js
  panda-office/src/components/common/Navbar.js
  panda-office/src/modules/PayrollModules.js
  panda-office/src/pages/Employee/Payroll/EmplPayroll.css
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
  panda-office/src/pages/Employee/Payroll/MyPay.css
  panda-office/src/pages/Employee/Payroll/MyPay.js
  panda-office/src/pages/main/Main.js
Labels: 기능구현잇슈, 이유란

#91 [기능구현] 내 근태 현황 API 연동 성공
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/modules/AttendanceModules.js
  panda-office/src/modules/index.js
  panda-office/src/pages/attendance/AttendanceSidebar.js
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.css
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.js
Labels: 기능구현잇슈, 손석현

#97 [기능 구현] 내 연차 내역 API 연동 완료[이게 먼저임!]
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/modules/AttendanceModules.js
  panda-office/src/pages/attendance/annualleaverecord/AnnualLeaveRecord.css
  panda-office/src/pages/attendance/annualleaverecord/AnnualLeaveRecord.js
  panda-office/src/pages/attendance/annualleaverecord/Current.js
  panda-office/src/pages/attendance/annualleaverecord/Search.js
Labels: 기능구현잇슈, 손석현

#98 [오류해결] 사원 급여 등록 수정
  panda-office/src/apis/PayrollAPICalls.js
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
  panda-office/src/utils/CalendarApi.js
Labels: 버그해결햇슈, 이유란

#96 [기능구현] 내 근태 신청현황 API 연동하기
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/modules/AttendanceModules.js
  panda-office/src/pages/attendance/attendancerequeststatus/AttendanceRequestStatus.css
  panda-office/src/pages/attendance/attendancerequeststatus/AttendanceRequestStatus.js
  panda-office/src/pages/attendance/attendancerequeststatus/Current.js
  panda-office/src/pages/attendance/attendancerequeststatus/Search.js
Labels: 기능구현잇슈, 손석현

#100 [기능 구현] 캘린더 db 일정 등록 구현
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/apis/InterviewScheduleAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/modules/InterviewScheduleModules.js
  panda-office/src/pages/recruitment/applicant/Applicant.js
  panda-office/src/pages/recruitment/applicant/ApplicantCreateModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantList.js
  panda-office/src/pages/recruitment/applicant/ApplicantListItem.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantSearch.js
  panda-office/src/pages/recruitment/schedule/Intertviewer.js
  panda-office/src/pages/recruitment/schedule/InterviewerAddList.js
  panda-office/src/pages/recruitment/schedule/SchedulDetailModal.js
  panda-office/src/pages/recruitment/schedule/Schedule.js
  panda-office/src/pages/recruitment/schedule/ScheduleCreate.js
  panda-office/src/pages/recruitment/schedule/ScheduleForm.js
  panda-office/src/pages/recruitment/schedule/ScheduleModal.js
  panda-office/src/utils/CalendarApi.js
Labels: 기능구현잇슈, 성우현

#101 [기능 구현] 출퇴근 기능 API 연동하기
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/components/common/AttendanceHandler.js
  panda-office/src/components/common/Navbar.js
  panda-office/src/modules/AttendanceModules.js
Labels: 기능구현잇슈, 손석현

#102 [기능 구현] 캘린더 이벤트 클릭 모달창 조회 구현
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/apis/InterviewScheduleAPICalls.js
  panda-office/src/modules/ApplicantModules.js
  panda-office/src/modules/InterviewScheduleModules.js
  panda-office/src/pages/recruitment/PagingBar.js
  panda-office/src/pages/recruitment/RecruitmentLayout.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/recruitment/applicant/ApplicantCreateModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/recruitment.css
  panda-office/src/pages/recruitment/schedule/InterviewerAddList.js
  panda-office/src/pages/recruitment/schedule/SchedulDetailModal.js
  panda-office/src/pages/recruitment/schedule/Schedule.js
  panda-office/src/pages/recruitment/schedule/ScheduleForm.js
  panda-office/src/pages/recruitment/schedule/ScheduleModal.js
  panda-office/src/utils/CalendarApi.js
Labels: 기능구현잇슈, 성우현

#104 [버그 이슈] 오타 및 오류 해결함
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/modules/AttendanceModules.js
Labels: 버그해결햇슈, 손석현

#105 [기능구현] 공지사항 조회, 상세, 등록 페이지 구현
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/apis/NoticeAPICalls.js
  panda-office/src/modules/NoticeModules.js
  panda-office/src/pages/notice/CategoryNoticeList.js
  panda-office/src/pages/notice/Notice.js
  panda-office/src/pages/notice/NoticeLayout.js
  panda-office/src/pages/notice/NoticeList.js
  panda-office/src/pages/notice/NoticeListItem.js
  panda-office/src/pages/notice/NoticePagingBar.js
  panda-office/src/pages/notice/NoticeRegist.js
  panda-office/src/pages/notice/NoticeRoutes.js
  panda-office/src/pages/notice/NoticeSidebar.js
  panda-office/src/pages/notice/detailNotice/NoticeDetail.js
  panda-office/src/pages/notice/notice.css
Labels: 기능구현잇슈, 김민준

#107 [기능 구현] 면접관 호출 api uri 수정
  package-lock.json
  panda-office/src/apis/InterviewScheduleAPICalls.js
  panda-office/src/pages/recruitment/schedule/ScheduleModal.js
  panda-office/src/utils/CalendarApi.js
Labels: 버그잇슈, 버그해결햇슈, 성우현

#110 [기능구현] 연차 조정 API 연동하기
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/modules/AttendanceModules.js
  panda-office/src/pages/attendance/annualleaveadjustment/AnnualLeaveAdjustment.css
  panda-office/src/pages/attendance/annualleaveadjustment/AnnualLeaveAdjustment.js
  panda-office/src/pages/attendance/annualleaveadjustment/AnnualLeaveHistory.js
  panda-office/src/pages/attendance/annualleaveadjustment/AnnualLeaveHistoryWithAdjustment.css
  panda-office/src/pages/attendance/annualleaveadjustment/AnnualLeaveHistoryWithAdjustment.js
  panda-office/src/pages/attendance/annualleaveadjustment/LeaveAdjustment.css
  panda-office/src/pages/attendance/annualleaveadjustment/LeaveAdjustment.js
  panda-office/src/pages/attendance/annualleaverecord/Search.js
  panda-office/src/pages/attendance/attendancestatus/AttendanceStatus.js
Labels: 기능구현잇슈, 손석현

#111 [기능구현] 인사 부서 접근 페이지 설정
  panda-office/src/components/common/Navbar.js
  panda-office/src/pages/Employee/AddNewEmployee.js
  panda-office/src/pages/Employee/EditEmployee.js
  panda-office/src/pages/Employee/Employee.css
  panda-office/src/pages/Employee/EmployeeDetail.js
  panda-office/src/pages/Employee/EmployeeList.js
  panda-office/src/pages/Employee/EmployeeRoutes.js
  panda-office/src/pages/Employee/EmployeeSidebar.js
  panda-office/src/pages/LoginForm/LoginForm.css
  panda-office/src/pages/LoginForm/LoginForm.js
  panda-office/src/pages/LoginForm/ResetPasswordModal.js
  panda-office/src/pages/LoginForm/TermsOfUseModal.js
  panda-office/src/pages/LoginForm/UseOfPersonalInfoModal.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/utils/TokenUtils.js
Labels: 기능구현잇슈, 김아연

#112 [기능구현] 전자결재 기안, 템플릿, 결재 구현
  panda-office/src/apis/e_approval/ApprovalDocumentAPICalls.js
  panda-office/src/apis/e_approval/ApprovalDocumentFolderAPICalls.js
  panda-office/src/apis/e_approval/ApprovalDocumentTemplateAPICalls.js
  panda-office/src/components/e_approval/document/ApprovalDocument.js
  panda-office/src/components/e_approval/document/ApprovalDocumentInfo.js
  panda-office/src/components/e_approval/document/ApprovalLine.js
  panda-office/src/components/e_approval/draft/AddNewLine.js
  panda-office/src/components/e_approval/draft/AddNewLinePreview.js
  panda-office/src/components/e_approval/draft/ApprovalBox.js
  panda-office/src/components/e_approval/draft/CurrentLine.js
  panda-office/src/components/e_approval/draft/DocumentEditor.js
  panda-office/src/components/e_approval/draft/DocumentSetting.js
  panda-office/src/components/e_approval/modal/ApprovalModal.js
  panda-office/src/components/e_approval/modal/DraftModal.js
  panda-office/src/components/e_approval/modal/FolderChangeModal.js
  panda-office/src/components/e_approval/modal/FolderSelect.js
  panda-office/src/components/e_approval/modal/TemplateSelect.js
  panda-office/src/components/e_approval/modal/modal.css
  panda-office/src/components/e_approval/template/DraftApprovalLine.js
  panda-office/src/components/e_approval/template/TempApprovalLine.js
  panda-office/src/components/e_approval/template/TemplateEditor.js
  panda-office/src/components/e_approval/template/TemplateSetting.js
  panda-office/src/components/e_approval/template/components/AddNewLinePreview.js
  panda-office/src/components/e_approval/template/components/ApprovalDocumentSetting.js
  panda-office/src/components/e_approval/template/components/DraftApprovalBox.js
  panda-office/src/components/e_approval/template/components/DraftBox.js
  panda-office/src/components/e_approval/template/components/DraftInfo.js
  panda-office/src/components/e_approval/template/components/IntegrationTable.js
  panda-office/src/components/e_approval/template/components/TempAddNewLine.js
  panda-office/src/components/e_approval/template/components/TempApprovalBox.js
  panda-office/src/components/e_approval/template/components/TempCurrentLine.js
  panda-office/src/components/e_approval/template/components/WebEditor.js
  panda-office/src/components/e_approval/templateFolder/Folder.js
  panda-office/src/components/e_approval/templateFolder/FolderList.js
  panda-office/src/components/e_approval/templateFolder/FolderManager.js
  panda-office/src/components/e_approval/templateFolder/TemplateFolder.js
  panda-office/src/components/e_approval/templateFolder/TemplateManager.js
  panda-office/src/components/e_approval/templateFolder/TemplateTable.js
  panda-office/src/modules/E_ApprovalModules.js
  panda-office/src/pages/e_approval/E_Approval.css
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/E_ApprovalSidebar.js
  panda-office/src/pages/e_approval/document/DraftDocument.js
  panda-office/src/pages/e_approval/document/ViewDocument.js
  panda-office/src/pages/e_approval/documentTemplate/E_ApprovalTemplateFolder.js
  panda-office/src/pages/e_approval/documentTemplate/E_ApprovalTemplateRegist.js
  panda-office/src/pages/main/Main.js
Labels: 기능구현잇슈, 편승준

#117 [기능 구현] 면접일정 수정 기능 구현
  panda-office/src/apis/ApplicantAPICalls.js
  panda-office/src/apis/InterviewScheduleAPICalls.js
  panda-office/src/pages/recruitment/RecruitmentLayout.js
  panda-office/src/pages/recruitment/applicant/ApplicantCreateModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantInfoTitle.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantSearch.js
  panda-office/src/pages/recruitment/recruitment.css
  panda-office/src/pages/recruitment/schedule/SchedulDetailModal.js
  panda-office/src/utils/CalendarApi.js
Labels: 기능구현잇슈, 성우현

#114 [기능구현] 공지사항 조회, 등록 수정 보안
  panda-office/src/apis/NoticeAPICalls.js
  panda-office/src/modules/NoticeModules.js
  panda-office/src/pages/notice/Notice.js
  panda-office/src/pages/notice/NoticePagingBar.js
  panda-office/src/pages/notice/NoticeRegist.js
Labels: 기능구현잇슈, 김민준

#123 [기능구현] 연차 캘린더 API 연동하기
  panda-office/src/App.js
  panda-office/src/apis/AttendanceAPICalls.js
  panda-office/src/components/main/calender/AnnualLeaveCalendar.css
  panda-office/src/components/main/calender/AnnualLeaveCalendar.js
  panda-office/src/components/main/calender/Calendar.js
  panda-office/src/components/main/calender/Modal.js
  panda-office/src/modules/AttendanceModules.js
  panda-office/src/pages/main/Main.js
  panda-office/src/pages/recruitment/schedule/ScheduleCreate.js
Labels: 기능구현잇슈, 손석현

#121 [기능구현] 공지사항 조회, 등록 수정 보완
  panda-office/src/apis/NoticeAPICalls.js
  panda-office/src/pages/notice/CategoryNoticeList.js
  panda-office/src/pages/notice/Notice.js
  panda-office/src/pages/notice/NoticeRegist.js
Labels: 기능구현잇슈, 김민준

#125 [기능구현] 결재서류 API 호출
  panda-office/src/apis/e_approval/ApprovalDocumentAPICalls.js
  panda-office/src/components/e_approval/document/DocumentCriteria.js
  panda-office/src/components/e_approval/document/DocumentTable.js
  panda-office/src/components/e_approval/draft/DocumentSetting.js
  panda-office/src/components/e_approval/template/TemplateSetting.js
  panda-office/src/modules/E_ApprovalModules.js
  panda-office/src/pages/e_approval/E_Approval.css
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/document/DocumentList.js
  panda-office/src/pages/e_approval/document/DraftDocument.js
  panda-office/src/pages/e_approval/documentTemplate/E_ApprovalTemplateRegist.js
Labels: 기능구현잇슈, 편승준

#120 #119 사원 급여관리(자료입력&개인조회) 구현
  panda-office/src/apis/PayrollAPICalls.js
  panda-office/src/modules/PayrollModules.js
  panda-office/src/pages/Employee/Payroll/EmplPayroll.css
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
  panda-office/src/pages/Employee/Payroll/MyPay.css
  panda-office/src/pages/Employee/Payroll/MyPay.js
Labels: 기능구현잇슈, 꾸며봣슈, 이유란

#124 [기능구현]설문 페이지 구현 및 기능 구현
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/components/common/Header.js
  panda-office/src/components/common/Navbar.js
  panda-office/src/components/main/card/Card.js
  panda-office/src/components/welfare/Dashboard.css
  panda-office/src/components/welfare/Dashboard.js
  panda-office/src/components/welfare/SurveyProgress.js
  panda-office/src/components/welfare/SurveyRegistration.js
  panda-office/src/components/welfare/Test.js
  panda-office/src/components/welfare/charts/QuestionChart.js
  panda-office/src/pages/main/Main.js
  panda-office/src/pages/welfare/WelfareRoutes.js
  panda-office/src/pages/welfare/WelfareSidebar.js
  panda-office/src/pages/welfare/welfare.css
  panda-office/src/style.css
Labels: 기능구현잇슈, 신동우

#128 [기능 구현] CSS 및 컴포넌트 수정
  panda-office/src/App.js
  panda-office/src/components/main/calender/AnnualLeaveCalendar.css
  panda-office/src/pages/main/Main.js
  panda-office/src/pages/welfare/WelfareSidebar.js
Labels: 기능구현잇슈, 성우현

#130 [오류 해결] 채용면접 컴포넌트 권한 해제 및 파비콘, 타이틀 수정
  panda-office/public/index.html
  panda-office/public/pandaOffice_logo.png
  panda-office/src/components/common/Navbar.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/recruitment/RecruitmentSidebar.js
Labels: 버그해결햇슈, 성우현

#132 [기능 수정] 중복 클래스 네임 수정
  panda-office/src/pages/recruitment/applicant/ApplicantCreateModal.js
  panda-office/src/pages/recruitment/applicant/ApplicantModal.js
  panda-office/src/pages/recruitment/recruitment.css
Labels: 꾸며봣슈, 성우현

#134 프론트 리드미 파일 업데이트
  README.md
Labels: 기타사항잇슈, 신동우

#135 PandaOffice_front_readme_update2
  README.md
Labels: 기타사항잇슈, 신동우

#136 [리드미수정] 리드미 파일 수정
  README.md
Labels: 기타사항잇슈, 신동우
