Repository ErrorCode-510/PandaOffice_front, pull requests merged in 2024-06, with the labels that each got.

#11 [기능구현] 메인 페이지 구현 및 로그인 페이지 연결
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/public/image/logo/logo_white.png
  panda-office/public/image/logo/pandaOffice_logo.png
  panda-office/src/App.js
  panda-office/src/components/Assets/LoginForm/LoginForm.css
  panda-office/src/components/Assets/LoginForm/LoginForm.jsx
  panda-office/src/components/common/Footer.js
  panda-office/src/components/common/Header.js
  panda-office/src/components/common/Navbar.js
  panda-office/src/components/main/announcement/Announcement.js
  panda-office/src/components/main/calender/Calendar.js
  panda-office/src/components/main/card/Card.js
  panda-office/src/index.css
  panda-office/src/index.js
  panda-office/src/layouts/Layout.js
  panda-office/src/modules/MemberModules.js
  panda-office/src/modules/OrderModules.js
  panda-office/src/modules/ProductModules.js
  panda-office/src/modules/ReviewModule.js
  panda-office/src/modules/index.js
  panda-office/src/modules/template.js
  panda-office/src/pages/main/Main.js
  panda-office/src/store.js
  panda-office/src/style.css
  panda-office/src/utils/CalendarApi.js
  panda-office/src/utils/Clock.js
Labels: 기능구현잇슈, 성우현, 신동우, 이유란

#13 [기능구현] 로그인 화면 크기수정
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/public/favicon.ico
  panda-office/public/logo192.png
  panda-office/public/logo512.png
  panda-office/src/App.js
  panda-office/src/pages/LoginForm/LoginForm.css
  panda-office/src/pages/LoginForm/LoginForm.js
Labels: 꾸며봣슈, 이유란

#16 [기능구현] 만족도,민원 통계 페이지 레이아웃 구현 및 공통 레이아웃 분리
  panda-office/package-lock.json
  panda-office/package.json
  panda-office/src/App.js
  panda-office/src/common.css
  panda-office/src/components/welfare/statistics/StatisticsLeft.js
  panda-office/src/components/welfare/statistics/StatisticsRight.js
  panda-office/src/pages/welfare/statistics/Statistics.css
  panda-office/src/pages/welfare/statistics/Statistics.js
Labels: 기능구현잇슈, 신동우

#19 [오류 해결] Main.css 및 StaticsRight.js 파일을 찾을 수 없음
  panda-office/package-lock.json
  panda-office/src/App.js
  panda-office/src/common.css
  panda-office/src/pages/main/Main.css
  panda-office/src/pages/main/Main.js
  panda-office/src/pages/welfare/statistics/Statistics.js
  panda-office/src/style.css
Labels: 버그해결햇슈, 신동우

#20 Create README.md
  README.md
Labels: 기타사항잇슈

#25 [기능구현] 라우터 구조 수정
  panda-office/src/App.js
  panda-office/src/components/main/calender/Calendar.js
  panda-office/src/layouts/Layout.js
  panda-office/src/pages/Employee/Employee.js
  panda-office/src/pages/Employee/EmployeeLayout.js
  panda-office/src/pages/Employee/EmployeeRoutes.js
  panda-office/src/pages/Employee/EmployeeSidebar.js
  panda-office/src/pages/LoginForm/FindIdModal.js
  panda-office/src/pages/LoginForm/FindPasswordModal.js
  panda-office/src/pages/attendance/Attendance.js
  panda-office/src/pages/attendance/AttendanceLayout.js
  panda-office/src/pages/attendance/AttendanceRoutes.js
  panda-office/src/pages/attendance/AttendanceSidebar.js
  panda-office/src/pages/e_approval/E_ApprovalLayout.js
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/E_approval.js
  panda-office/src/pages/e_approval/E_approvalSidebar.js
  panda-office/src/pages/notice/Notice.js
  panda-office/src/pages/notice/NoticeLayout.js
  panda-office/src/pages/notice/NoticeRoutes.js
  panda-office/src/pages/notice/NoticeSidebar.js
  panda-office/src/pages/recruitment/Recruitment.js
  panda-office/src/pages/recruitment/RecruitmentLayout.js
  panda-office/src/pages/recruitment/RecruitmentRoutes.js
  panda-office/src/pages/welfare/Welfare.js
  panda-office/src/pages/welfare/WelfareLayout.js
  panda-office/src/pages/welfare/WelfareRoutes.js
  panda-office/src/pages/welfare/WelfareSidebar.js
  panda-office/src/style.css
  panda-office/src/utils/CalendarApi.js
Labels: 꾸며봣슈, 편승준

#26 [기능구현] approval->Approval 대문자 수정
  panda-office/src/pages/e_approval/E_ApprovalSidebar.js
Labels: 기타사항잇슈, 편승준

#29 [기능구현] 전자결재 탭 사이드바 기능 구현
  panda-office/src/apis/E_ApprovalAPICalls.js
  panda-office/src/apis/api.js
  panda-office/src/modules/E_ApprovalModules.js
  panda-office/src/modules/index.js
  panda-office/src/pages/e_approval/E_ApprovalRoutes.js
  panda-office/src/pages/e_approval/E_ApprovalSidebar.js
  panda-office/src/pages/notice/NoticeLayout.js
  panda-office/src/style.css
Labels: 기능구현잇슈, 편승준

#31 [기능구현] 사원 급여 개인 조회 페이지 구현
  panda-office/src/pages/Employee/EmployeeLayout.js
  panda-office/src/pages/Employee/EmployeeRoutes.js
  panda-office/src/pages/Employee/EmployeeSidebar.js
  panda-office/src/pages/Employee/Payroll/EmplPayroll.css
  panda-office/src/pages/Employee/Payroll/EmplPayroll.js
  panda-office/src/pages/Employee/Payroll/MyPay.css
  panda-office/src/pages/Employee/Payroll/MyPay.js
  panda-office/src/style.css
Labels: 꾸며봣슈, 이유란
